services:
  - type: web
    name: fresh-fold-api
    runtime: node
    rootDir: fresh-and-fold-backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: "10000"
